language: node_js
sudo: true
node_js: '8'
cache:
  directories:
  - node_modules
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_c8941efc9809_key -iv $encrypted_c8941efc9809_iv -in .env.enc -out .env -d || true'
script:
- npm run build
- npm run lint
- npm run codecov
env:
  global:
  - BX_APP=assistant-with-discovery-openwhisk-demo
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
deploy:
- provider: script
  skip_cleanup: true
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/assistant-with-discovery-openwhisk
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8